server:
  port: 8082
  servlet:
    context-path: /api

spring:
  # 数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://101.42.1.209:3306/youqsd_manage_prod
    driver-class-name: com.mysql.cj.jdbc.Driver


    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      max-active: 30
      min-idle: 6
      max-wait: 15000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 0
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 打印完整sql
      filter:
        slf4j:
          enabled: true
          statementPrepareAfterLogEnabled: false
          statementCreateAfterLogEnabled: false
          statementExecuteQueryAfterLogEnabled: false
          statementExecuteAfterLogEnabled: false
          statementParameterSetLogEnabled: false

          statementCloseAfterLogEnabled: false
          statementExecuteBatchAfterLogEnabled: false
          statementExecuteUpdateAfterLogEnabled: false
          statementPrepareCallAfterLogEnabled: false
          statementExecutableSqlLogEnable: true
          statementLogEnabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

logging:
  level:
    druid:
      sql:
        Statement: debug

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 123456
  timeout: 500ms
  lettuce:
    pool:
      max-active: 50
      max-wait: -1ms
      max-idle: 10
      min-idle: 2

swagger:
  enable: true
