spring:
  main:
    allow-circular-references: true
  profiles:
    # dev开发环境  prod正式环境
    active: test
  application:
    name: youqsd_manage
  aop:
    proxy-target-class: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  boot:
    admin:
      client:
        instance:
          name: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.wx.youqsd_manage.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    map-underscore-to-camel-case: true


management:
  server:
    add-application-context-header: false

wx:
  appId:
    wx5bfbae0d9f670d83
  appSecret:
    3c6faaccc38c8ad04ade2578afbbdf56
  loginUrl:
    https://api.weixin.qq.com/sns/jscode2session
  getphonenumber:
    https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token=
